config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, :controllers => { :registrations => 'registrations' } do
    get 'sign_out' => 'devise/session#destroy'
  end

  resources :users
  resources :friendships do
    member do
      put :accepted_friends
      put :rejected_friends
    end
  end
  resources :masseges
   get 'search/users'
  

   root 'users#index'

end

app/models/friend_request.rb
class FriendRequest < ActiveRecord::Base
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => 'User',:foreign_key =>'friend_id'


	def self.check_friendship(sender_id, receiver_id)
		where("(user_id=? and friend_id=?) or (friend_id=? and user_id=?)", sender_id, receiver_id, sender_id, receiver_id).first
	end
end

app/models/massege.rb
class Massege < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /image/

#has_many :friendships, :dependent => :destroy
#has_many :pending_friends,  -> {where(status: 'pending')}, through: :friendships
#has_many :requested_friends, -> {where(status: 'requested')},through: :friendships
#has_many :accepted_friends, -> { where(status: 'accepted') }, through: :friendships
#has_many :rejected_friends, -> { where(status: 'rejected') }, through: :friendships
has_many :friendships  
has_many :friends, :through => :friendships 
has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"  
has_many :inverse_friends, :through => :inverse_friendships, :source => :user  

has_many :masseges


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  #before_filter :login_required, :except => [:index]
  
  def index
    if params[:find_friend_string].present?
      @users = User.where(email: params[:find_friend_string])
    else
      @users = User.includes(:friendships)
    end
    @user = current_user
    @friendship = Friendship.where(friend_id: current_user.id)
    #@friendships = Friendship.all  
  end

  def create
      @friendship = current_user.friendships.new(:friend_id => params[:friend_id], status: 'pending')
      @friendship.save!
      redirect_to friendships_url
  end

  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    flash[:notice] = "Removed friendship."
    redirect_to friendships_path
  end

  def accepted_friends
     @friendship = Friendship.find(params[:id])
     @friendship.update(status: "accepted")
    redirect_to friendships_path
  end

  def rejected_friends
     @friendship = Friendship.find(params[:id])
     @friendship.update(status: "rejected")
    redirect_to friendships_path
  end 

   
end

app/controllers/masseges_controller.rb
class MassegesController < ApplicationController

	def index 
       @masseges = Massege.where(friend_id: current_user.id, user_id: params[:friend_id])
       @massege = Massege.new
  end 

    
    
  def create  
    @massege = Massege.create!(massege_params)
    redirect_to masseges_path(friend_id: params[:massege][:friend_id]) 
  end


  
  private

 	def massege_params
 		params.require(:massege).permit(:user_id, :friend_id, :body)
 	end
end

app/controllers/registrations_controller.rb
class RegistrationsController <  Devise::RegistrationsController

	def sign_up_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, :avatar, :date_of_birth)
  end
 
  def account_update_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, :avatar, :date_of_birth)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  

  def index

    if params[:find_friend_string].present?
      @users = User.where(email: params[:find_friend_string])
    else
      @users = User.includes(:friendships)
    end
    @user = current_user
  end


  def edit
    @user = User.find(params[:id])
   end

 
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render "edit"
    end
  end

private
  
  def user_params
    params.require(:user).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/massege_helper.rb
module MassegeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/index.html.erb
<% @users.each do |user| %>
<%#= user.id %>
<% unless user == current_user %>
<div class="table table-bordered" >
<table>      
<tr>

<th><%= user.email %></th>
<td>
<% friendship = Friendship.check_friendship(user.id, current_user.id) %>
<% if friendship.present?%>
<% if friendship.friend_id == current_user.id && friendship.status == "pending" %>
<%= link_to "Accept", accepted_friends_friendship_path(friendship), :method => :put %>
<%= link_to "reject", rejected_friends_friendship_path(friendship), :method => :put %>
<% elsif friendship.status == "accepted" %>
<b>Friendship</b>
<% elsif friendship.status == "rejected" %>
Rejected Friend
<% end %>
<% else %>
<%= link_to "Add Friend",friendships_path(:friend_id => user), :method => :post,:class =>"btn btn-info" %>
<% end %> |
<%= link_to "Send Message" , masseges_path(:friend_id => user),:method => :get,:class =>"btn btn-success" %>
</td>
</tr>
</table>
</div>
<% end %>
<% end %>
<h2>Friends</h2>
<ul>
<% for friendship in @user.friendships %>
<li>
<%= User.find(friendship.friend_id).first_name%>
<%#if friendship.present? %>
<%= link_to "remove", friendship, :method => :delete,:class=>"btn btn-info" %>
<% end %>
<%#end %>
</li>
</ul></br>
<%= link_to "back",users_path,:class => "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Facebook" %></title>
    <%= csrf_meta_tags %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
       <%= link_to "Facebook","#", :style => "font-size:30px;" %>
         
 
        <div class="pull-right">
        <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete,:class=> "btn btn-primary") %>       
            <% else %>
              <%#= link_to('Login', new_user_session_path)  %> 
            <% end %>
        </div>
      </div>
    </div> 
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div>
      </div><!--/row-->

      
    </div> <!-- /container -->

  </body>
</html>

app/views/masseges/create.js.erb
    $("#chat").append("<%= escape_javascript render(@message) %>");  
    $("#new_message")[0].reset();  

app/views/masseges/index.html.erb
<% @masseges.each do |massege| %>
	<%= massege.body %>
	
<% end %>

<%= form_for @massege do |f| %> 
<%= f.hidden_field  :friend_id, value: params[:friend_id] %>
<%= f.hidden_field :user_id, value: current_user.id %>
  <div class="row">
  <div class=" large-3 columns">
<%= f.text_area :body %>
</div>
</div>
  
<%= f.submit  "send message",:class=>"btn btn-success"%>
<% end %><br>
<%= link_to "back", friendships_path,:class=>"btn btn-primary" %>

app/views/users/_form.html.erb
<%= form_for :user, url: "/users/#{@user.id}", method: :put,:html => { :multipart => true } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
  <div class=" large-3 columns">
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>
  </div>
  </div>

  <div class="row">
  <div class=" large-3 columns">
  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>
  </div>
</div>
  <div class="row">
  <div class=" large-3 columns">
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
  </div>
</div>

  <div class="row">
  <div class=" large-3 columns">
  <p>
    <%= f.label :date_of_birth %><br>
    <%= f.text_field :date_of_birth %>
  </p>
  </div>
</div>
  
  <div class="row">
  <div class=" large-3 columns">
  <%= f.file_field :avatar %>
  </p>
  </div>
</div>
<div class="row">
  <div class=" large-3 columns">
  <%= f.button :submit , :class=>"btn btn-info" %>
  <% end %>
  </div><br>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>
 
<%= render 'form' %>

 
<%= link_to 'Back', users_path, :class=>"btn btn-primary" %>

app/views/users/index.html.erb
  <div class="large-4 row">
  <div class=" large-3 columns"></div>
  <div class=" large-4 columns"></div>
    <span style="text-align: right">
     <%= form_tag :friendships,url: friendships_path,:method=>'get' do %>
       <%= text_field_tag :find_friend_string %>
       <%= submit_tag  "Find Friend",:class=>"btn btn-info" %>
     <% end %>
    </span>
    </div>
  <%= link_to "Add-friend",friendships_path(@friendship),:class=>"btn btn-info" %>

  

<table>
  <tr>
    <th>&nbsp;</th>
    <td>
      <%= image_tag(@user.avatar) %>
    </td>
  </tr><br>
  <tr>
    <th>First Name</th>
    <td>
      <%= @user.first_name %>
    </td>
  </tr><br>
  <tr>
    <th>Last Name</th>
    <td>
      <%= @user.last_name %>
    </td>
  </tr><br>
  <tr>
    <th>Email</th>
    <td>
      <%= @user.email %>
    </td>
  </tr><br>
  <tr>
    <th>Date of birth</th>
    <td>
      <%= @user.date_of_birth %>
    </td>
  </tr>
  
  <td><%= link_to 'Edit', edit_user_path(@user), :class=>"btn btn-primary" %></td>
  <td><%= link_to 'back',friendships_path,:class=>"btn btn-primary" %></td>
</table>